"""empty message

Revision ID: 81f79e9b7e69
Revises: 
Create Date: 2024-04-19 13:08:52.858670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f79e9b7e69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_underbody')
    op.drop_table('tb_seats')
    op.drop_table('tb_hybrid')
    op.drop_table('tb_carpet_trim_mats')
    op.drop_table('tb_transmission_differential')
    op.drop_table('tb_luggage_compartment')
    op.drop_table('tb_underhood')
    op.drop_table('tb_airbag_safety_belts')
    op.drop_table('tb_brake')
    op.drop_table('tb_fluids')
    op.drop_table('tb_road')
    op.drop_table('tb_glass_outside_mirrors')
    op.drop_table('tb_fuel_system')
    op.drop_table('tb_diagnostic')
    op.drop_table('tb_doors_hood_tailgate')
    op.drop_table('tb_engine')
    op.drop_table('tb_grille_trim_roof_rack')
    op.drop_table('tb_exterior')
    op.drop_table('tb_exterior_lights')
    op.drop_table('tb_audio_alarm')
    op.drop_table('tb_interior')
    op.drop_table('tb_tires_wheels')
    op.drop_table('tb_checklist')
    op.drop_table('tb_cooling_system')
    op.drop_table('tb_body_bumper')
    op.drop_table('tb_sunroof_convertible_top')
    op.drop_table('tb_exhaust_system')
    op.drop_table('tb_interior_amenities')
    op.drop_table('tb_engine_electrical_system')
    op.drop_table('tb_windows_door_locks')
    op.drop_table('tb_invoice')
    op.drop_table('tb_heat_ac_defog_defrost')
    op.drop_table('tb_frame')
    with op.batch_alter_table('tb_ownership', schema=None) as batch_op:
        batch_op.drop_constraint('tb_ownership_owner_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('tb_ownership_vehicle_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_vehicle', ['vehicle_id'], ['id'], referent_schema='checklist_app', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tb_owner', ['owner_id'], ['id'], referent_schema='checklist_app', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_ownership', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_ownership_vehicle_id_fkey', 'tb_vehicle', ['vehicle_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('tb_ownership_owner_id_fkey', 'tb_owner', ['owner_id'], ['id'], ondelete='CASCADE')

    op.create_table('tb_frame',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('frame_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('frame_damage', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('fuel_supply_system', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='frame_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tb_heat_ac_defog_defrost',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('heat_ac_defog_defrost_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('ac_system', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('heating_system', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('defog_defrost', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='heat_ac_defog_defrost_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tb_invoice',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vehicle', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('checklist', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['checklist'], ['tb_checklist.id'], name='checklist'),
    sa.PrimaryKeyConstraint('id', name='invoice_pkey')
    )
    op.create_table('tb_windows_door_locks',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('windows_door_locks_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('door_handles_release', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('remote_entry', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('push_button_start', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('door_locks', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('child_safety_locks', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('window_controls', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('remote_decklid_release', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('fuel_filler_door_release', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='windows_door_locks_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tb_engine_electrical_system',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('engine_electrical_system_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('starter', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('ignition', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('battery', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('alternator_output', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('diesel_glow_plug_system', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='engine_electrical_system_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tb_interior_amenities',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('interior_amenities_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('clock', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('tilt_telescopic_steering_wheel', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('steering_column_lock', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('horn', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('warning_chimes', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('instrument_panel_warning_lights', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('windshiel_wipers', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('washers', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('interior_courtesy_dome_lights', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('rear_view_mirror', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('auto_diming_rear_view_mirror', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('blis', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('rear_view_camera_system', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('active_park_assist', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('rear_entertainment_system', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('power_outlets', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('lighter', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('ashtrays', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('glovebox', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('center_arm_rest_console', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('sunvisors', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('adjustable_pedals', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='interior_amenities_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tb_exhaust_system',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('exhaust_system_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('exhaust_system_condition', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('emissions_control', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='exhaust_system_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tb_sunroof_convertible_top',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('sunroof_convertible_top_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('sunroof', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('convertible_top', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sunroof_convertible_top_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tb_body_bumper',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('body_bumper_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('flood_damage', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('fire_damage', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('major_damage', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('body_panel', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('bumper', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='body_bumper_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tb_cooling_system',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('cooling_system_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('radiator', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('pressure_test_radiator_cap', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('cooling_fans', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('water_pump', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('coolant_recovery_tank', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('cabin_air_filter', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cooling_system_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tb_checklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('diagnostic', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('underhood', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('underbody', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exterior', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interior', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hybdrid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('road', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['diagnostic'], ['tb_diagnostic.id'], name='diagnostic'),
    sa.ForeignKeyConstraint(['exterior'], ['tb_exterior.id'], name='exterior'),
    sa.ForeignKeyConstraint(['hybdrid'], ['tb_hybrid.id'], name='hybdrid'),
    sa.ForeignKeyConstraint(['interior'], ['tb_interior.id'], name='interior'),
    sa.ForeignKeyConstraint(['road'], ['tb_road.id'], name='road'),
    sa.ForeignKeyConstraint(['underbody'], ['tb_underbody.id'], name='underbody'),
    sa.ForeignKeyConstraint(['underhood'], ['tb_underhood.id'], name='underhood'),
    sa.PrimaryKeyConstraint('id', name='checklist_pkey')
    )
    op.create_table('tb_tires_wheels',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tires_wheels_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('tires_match_size', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('wheels_match_size', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('twi_front_lr', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('twi_rear_lr', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('tire_pressure_front_lr', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('tire_pressure_rear_lr', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('tire_pressure_system', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('wheels', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('wheels_covers', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('rack_pinion_linkage_boots', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('control_arms_bushing_ball_joints', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('tie_rods_idler_arm', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('springs', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('struts_shocks', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('wheel_alignment', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('power_steering_pump', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tires_wheels_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tb_interior',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('airbag_safety_belts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('audio_alarm', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('heat_ac_defog_defrost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interior_amenities', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('carpet_trim_mats', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seats', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sunroof_convertible_top', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('windows_door_locks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('luggage_compartment', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['airbag_safety_belts'], ['tb_airbag_safety_belts.id'], name='airbag_safety_belts'),
    sa.ForeignKeyConstraint(['audio_alarm'], ['tb_audio_alarm.id'], name='audio_alarm'),
    sa.ForeignKeyConstraint(['carpet_trim_mats'], ['tb_carpet_trim_mats.id'], name='carpet_trim_mats'),
    sa.ForeignKeyConstraint(['heat_ac_defog_defrost'], ['tb_heat_ac_defog_defrost.id'], name='heat_ac_defog_defrost'),
    sa.ForeignKeyConstraint(['interior_amenities'], ['tb_interior_amenities.id'], name='interior_amenities'),
    sa.ForeignKeyConstraint(['luggage_compartment'], ['tb_luggage_compartment.id'], name='luggage_compartment'),
    sa.ForeignKeyConstraint(['seats'], ['tb_seats.id'], name='seats'),
    sa.ForeignKeyConstraint(['sunroof_convertible_top'], ['tb_sunroof_convertible_top.id'], name='sunroof_convertible_top'),
    sa.ForeignKeyConstraint(['windows_door_locks'], ['tb_windows_door_locks.id'], name='windows_door_locks'),
    sa.PrimaryKeyConstraint('id', name='interior_pkey')
    )
    op.create_table('tb_audio_alarm',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('radio_cd_speaker', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('antenna', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('alarma_system', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('navigation_system', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='audio_alarm_pkey')
    )
    op.create_table('tb_exterior_lights',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('exterior_lights_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('front_lights', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('back_lights', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('side_lights', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('hazard_lights', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('auto_onoff_lighting', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('trailer_camp_connector', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='exterior_lights_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tb_exterior',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('body_bumper', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('doors_hood_tailgate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grille_trim_roof_rack', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('glass_outsidemirror', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lights', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['body_bumper'], ['tb_body_bumper.id'], name='body_bumper'),
    sa.ForeignKeyConstraint(['doors_hood_tailgate'], ['tb_doors_hood_tailgate.id'], name='doors_hood_tailgate'),
    sa.ForeignKeyConstraint(['glass_outsidemirror'], ['tb_glass_outside_mirrors.id'], name='glass_outsidemirror'),
    sa.ForeignKeyConstraint(['grille_trim_roof_rack'], ['tb_grille_trim_roof_rack.id'], name='grille_trim_roof_rack'),
    sa.ForeignKeyConstraint(['lights'], ['tb_exterior_lights.id'], name='lights'),
    sa.PrimaryKeyConstraint('id', name='exterior_pkey')
    )
    op.create_table('tb_grille_trim_roof_rack',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('grille', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('trim_inspection', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('roof_rack', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='grille_trim_roof_rack_pkey')
    )
    op.create_table('tb_engine',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('engine_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('fluid_leaks', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('hoses_lines', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('belts', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('wiring', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('water_coolant_engine_oil', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('oil_pressure', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('cylinder_compression', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('timing_belts', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('engine_mounts', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('turbocharger', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='engine_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tb_doors_hood_tailgate',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doors_alignment', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('door_hinges', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('roof_inspection', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('hood_alignment', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('hood_release', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('hood_hinges', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('hood_gasstruts', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('tailgate_alignment', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('trunkgasstruts', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('powerlift_gate_operation', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='doors_hood_tailgate_pkey')
    )
    op.create_table('tb_diagnostic',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('modules', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='diagnostic_pkey')
    )
    op.create_table('tb_fuel_system',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('fuel_system_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('fuel_pump_noise', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('fuel_pump_pressure', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('fuel_filter', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('engine_air_filter', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='fuel_system_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tb_glass_outside_mirrors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('windshield', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('side_glass', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('rear_window', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('wiper_blade', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('outside_mirror', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('outside_mirror_folding', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='glass_outside_mirrors_pkey')
    )
    op.create_table('tb_road',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('engine_starts', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('engine_idle', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('remote_start_operation', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('engine_accelerate_cruise', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('engine_noise_cold_hot', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('transmission_shift_operation', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('transmission_noise_cold_hot', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('shift_interlock_operation', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('drive_axle_transfer_case_noise', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('clutch_operation', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('steering_operation', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('body_suspension_squeaks', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('struts_shocks_operation', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('brake_abs_operation', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('cruise_control', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('gauges_operation', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('driver_select_memory_system', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('abnormal_wind_noise', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='road_pkey')
    )
    op.create_table('tb_fluids',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('fluids_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('engine_oil_filter', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('engine_oil', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('coolant', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('brake_fluid', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('automatic_transmission_fluid', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('transfercase_fluid', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('driveaxle_fluid', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('powersteering_fluid', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('manual_transmission_fluid', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('hydraulic_clutch_fluid', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('washer_fluid', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='fluids_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tb_brake',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('brake_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('calipers_wheel_cylinders', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('front_brake_pads_shoes', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('rear_brake_pads_shoes', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('rotors_drums', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('brake_lines_hoses_fittings', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('parking_brake', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('master_cylinder_booster', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='brake_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tb_airbag_safety_belts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('airbags', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('safety_belts', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='airbag_safety_belts_pkey')
    )
    op.create_table('tb_underhood',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fluids', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engine', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cooling_system', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fuel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engine_electrical_system', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cooling_system'], ['tb_cooling_system.id'], name='cooling_system'),
    sa.ForeignKeyConstraint(['engine'], ['tb_engine.id'], name='engine'),
    sa.ForeignKeyConstraint(['engine_electrical_system'], ['tb_engine_electrical_system.id'], name='engine_electrical_system'),
    sa.ForeignKeyConstraint(['fluids'], ['tb_fluids.id'], name='fluids'),
    sa.ForeignKeyConstraint(['fuel'], ['tb_fuel_system.id'], name='fuel'),
    sa.PrimaryKeyConstraint('id', name='underhood_pkey')
    )
    op.create_table('tb_luggage_compartment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('luggage_carpet', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('luggage_trim', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('luggage_light', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('jack_tool_kit', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('spare_tire_inspection', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('spare_tire_airpressure', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('tire_inflator_kit', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('emergency_trunk_lid', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='luggage_compartment_pkey')
    )
    op.create_table('tb_transmission_differential',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('transmission_differential_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('automatic_transmission', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('manual_transmission', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('hub_operation_4x4', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('universal_joints_cv_boots', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('transmission_mounts', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('differential_drive_axle', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='transmission_differential_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tb_carpet_trim_mats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('interior_free_ododr', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('carpet', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('floor_mats', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('door_trim_panels', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('headliner', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='carpet_trim_mats_pkey')
    )
    op.create_table('tb_hybrid',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cooling_system', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('powertrain_mount', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('information_display', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('power_outlet', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='hybrid_pkey')
    )
    op.create_table('tb_seats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('upholstery', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('seat_head_restraint_adjustment', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('folding_seats', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('heated_seats', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('cooled_seats', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('integrated_child_safety_seats', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='seats_pkey')
    )
    op.create_table('tb_underbody',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('frame', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exhaust_system', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transmission_differential', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tires_wheels', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('brakes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brakes'], ['tb_brake.id'], name='brakes'),
    sa.ForeignKeyConstraint(['exhaust_system'], ['tb_exhaust_system.id'], name='exhaust_system'),
    sa.ForeignKeyConstraint(['frame'], ['tb_frame.id'], name='frame'),
    sa.ForeignKeyConstraint(['tires_wheels'], ['tb_tires_wheels.id'], name='tires_wheels'),
    sa.ForeignKeyConstraint(['transmission_differential'], ['tb_transmission_differential.id'], name='transmission_differential'),
    sa.PrimaryKeyConstraint('id', name='underbody_pkey')
    )
    # ### end Alembic commands ###
